export const GET_USER_DATA_REQUEST = 'get/userData:request'
export const GET_USER_DATA_SUCCESS = 'get/userData:success'
export const GET_USER_DATA_ERROR = 'get/userData:error'
export const UPDATE_USER_DATA_REQUEST = 'update/userData:request'
export const UPDATE_USER_DATA_SUCCESS = 'update/userData:success'
export const UPDATE_USER_DATA_ERROR = 'update/userData:error'
